name: ForManu
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/google_icon.png 
    - assets/images/wifi.png
    - assets/images/category.png  
    - assets/images/hashtag.png 
    - assets/images/flash.png
    - assets/images/messages-2.png  
    - assets/images/user.png 
    - assets/images/2user.png 
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 500
